/*
 * Copyright (c) 2021 Friedt Professional Engineering Services, Inc
 *
 * SPDX-License-Identifier: MIT
 */

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>
#include <sys/macho_map.h>
#include <sys/debug.h>
#include <sys/printk.h>
#include <sys/__assert.h>

static uint8_t *get_list_start(const char *section_name);
static uint8_t *get_list_end(const char *section_name);
static size_t *get_list_offset(const char *section_name);

/* Generated by python for "fake" sections. Includes _list_start[] _list_end[] symbols, offsets, and empty space */
#include "macho_map.inc"

/* need to copy to _list_start[] / _list_end[] areas after runtime relocation */
void macho_map_append_to_section(const char *section_name, const void *data, size_t data_size)
{
    uint8_t *sect_start = get_list_start(section_name);
    uint8_t *sect_end = get_list_end(section_name);
    size_t *sect_offset = get_list_offset(section_name);

    __ASSERT(sect_start != NULL, "sect_start for section '%s' is NULL", section_name);
    __ASSERT(sect_end != NULL, "sect_end for section '%s' is NULL", section_name);
    __ASSERT(sect_offset != NULL, "sect_oiffset for section '%s' is NULL", section_name);
    __ASSERT(sect_start + *sect_offset + data_size <= sect_end, "append to section '%s' falls outside bounds", section_name);

    memcpy(sect_start + *sect_offset, data, data_size);
    *sect_offset += data_size;
}
